AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template - 3 EC2 Instances in 3 Selected Subnets

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  SubnetId1:
    Type: AWS::EC2::Subnet::Id
    Description: Select subnet for EC2 Instance 1

  SubnetId2:
    Type: AWS::EC2::Subnet::Id
    Description: Select subnet for EC2 Instance 2

  SubnetId3:
    Type: AWS::EC2::Subnet::Id
    Description: Select subnet for EC2 Instance 3

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SubnetId: !Ref SubnetId1
      Tags:
        - Key: Name
          Value: EC2-Instance-1

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SubnetId: !Ref SubnetId2
      Tags:
        - Key: Name
          Value: EC2-Instance-2

  EC2Instance3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SubnetId: !Ref SubnetId3
      Tags:
        - Key: Name
          Value: EC2-Instance-3

Outputs:
  EC2Instance1Id:
    Value: !Ref EC2Instance1

  EC2Instance2Id:
    Value: !Ref EC2Instance2

  EC2Instance3Id:
    Value: !Ref EC2Instance3
